AllCops:
  Exclude:
    - '*.md'
    - 'Gemfile'
    - 'Gemfile.lock'
    - db/schema.rb
    - config/**/*.rb
    - script/rails
  NewCops: enable

Layout/LineLength:
  Max: 130
  Exclude:
    - '*.gemspec'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/tmp/**/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/ParameterAlignment:
  EnforcedStyle: 'with_fixed_indentation'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'
